-- Declarative snapshot of the current public application tables in Supabase.

create table public.recurring_expenses (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  active boolean not null default true,
  start_month text not null,
  day_of_month integer not null,
  description text not null,
  category text not null,
  amount double precision not null,
  type text not null,
  "isPaidByKari" boolean not null default false,
  constraint recurring_expenses_day_of_month_check check (day_of_month between 1 and 31),
  constraint recurring_expenses_start_month_format_check check (start_month ~ '^\d{4}-(0[1-9]|1[0-2])$')
);

create table public.expenses (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  date date,
  description text,
  category text,
  amount double precision,
  type text,
  "isPaidByKari" boolean,
  is_default boolean not null default false,
  source_template_id bigint,
  constraint expenses_source_template_id_fkey
    foreign key (source_template_id) references public.recurring_expenses(id) on delete set null
);

create table public.income (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  kari_income double precision,
  adolfo_income double precision,
  total_income double precision,
  kari_percentage double precision,
  adolfo_percentage double precision,
  total_percentage double precision default 100,
  month_key text not null,
  constraint income_month_key_format_check check (month_key ~ '^\d{4}-(0[1-9]|1[0-2])$')
);

create table public.total_expenses (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  total double precision default 0,
  adolfo_total double precision default 0,
  kari_total double precision default 0,
  month_key text not null,
  constraint total_expenses_month_key_format_check check (month_key ~ '^\d{4}-(0[1-9]|1[0-2])$')
);

create table public.debt (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  adolfo_debt double precision default 0,
  kari_debt double precision default 0,
  month text,
  month_key text not null,
  constraint debt_month_key_format_check check (month_key ~ '^\d{4}-(0[1-9]|1[0-2])$')
);

create table public.debt_payments (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  paid_at date not null default current_date,
  payer text not null,
  recipient text not null,
  amount numeric(12,2) not null,
  note text,
  constraint debt_payments_payer_check check (payer in ('kari', 'adolfo')),
  constraint debt_payments_check check (recipient in ('kari', 'adolfo') and recipient <> payer),
  constraint debt_payments_amount_check check (amount > 0)
);

create table public.savings (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  "user" text default 'NULL',
  type text default 'NULL',
  amount double precision default 0,
  currency text
);

create unique index income_month_key_uidx on public.income (month_key);
create unique index total_expenses_month_key_uidx on public.total_expenses (month_key);
create unique index debt_month_key_uidx on public.debt (month_key);
create index expenses_source_template_id_idx on public.expenses (source_template_id);
create unique index recurring_expense_occurrence_uidx
  on public.expenses (source_template_id, date)
  where source_template_id is not null;
create unique index recurring_expenses_identity_uidx
  on public.recurring_expenses (lower(trim(description)), category, type, "isPaidByKari");
